version: "3"
services:
  db:
    image: "postgres"
    container_name: "caseIssuesDB"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
#   Set a volume some that database is not lost after shutting down the container.
#   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: "api"
    ports:
      # This is externalPort:internalPort, for the record
      - "8080:8080"
