logging:
  level:
      org.hibernate:
        SQL: DEBUG
        stat: ERROR
      gov.usds.case_issues: DEBUG
      org.springframework.security.access: DEBUG
spring:
  profiles:
    include: autotest-local
  datasource:
    username: case_issue_api
    url: jdbc:postgresql://localhost:${CASEISSUES_TEST_DB_PORT:5400}/case_issues
  jpa:
    properties:
      hibernate:
        default_schema: case_issue_main
        format_sql: true
        generate_statistics: false # way too noisy to be worth it
    hibernate.ddl-auto: none
  liquibase:
    enabled: true
    user: case_issue_migrations
web-customization:
  cors-origins:
    - http://ok-client.net
    - https://ok-client.gov
authorization:
  grants:
    - authentication-type: x509
      authorities: read-cases, update-cases, manage-application
      match-condition: 'CN=alice, O=No Such Agency, L=Washington, ST=DC, C=US'
      terminal: true
    - authentication-type: x509
      authorities: UPDATE_ISSUES
      match-condition:
        - 'CN=bob, O=No Such Agency, L=Washington, ST=DC, C=US'
      terminal: true
# this is probably not needed in the long run, but for now X509MappingConfig is conditional on it being set
server.ssl.client-auth: none
bind-testing:
  web-conf-a:
    cors-origins:
      - http://origin
      - https://other-origin
  web-conf-b:
    users:
      - name: user1
        grants:
          - READ_CASES
          - UPDATE_CASES
          - UPDATE_STRUCTURE
          - UPDATE_ISSUES
      - name: user2
  web-conf-c:
    users:
      - name: user1
        grants:
          - FAKE
          - UPDATE_CASES
  web-conf-d:
    data-formats:
      yabba:
        receipt-number-key: customReceiptNumber
      dabba:
        creation-date-key: "whenever"
      doo:
        creation-date-format: "EEE MMM dd yyyy" # Wed May 7 2031
  web-conf-e:
    additional-http-port: 23
  oauth-conf-a:
    name-path:
      - yabba
      - dabba
      - doo
    authority-paths:
      - authority: UPDATE_ISSUES
        path: custom, attribute, path
