logging:
  level:
      org.hibernate:
        SQL: DEBUG
        stat: ERROR
      gov.usds.case_issues: DEBUG
      org.springframework.security.access: DEBUG
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false # way too noisy to be worth it
    hibernate.ddl-auto: none
  liquibase:
    enabled: true
bind-testing:
  web-conf-a:
    cors-origins:
      - http://origin
      - https://other-origin
  web-conf-b:
    users:
      - name: user1
        grants:
          - READ_CASES
          - UPDATE_CASES
          - UPDATE_STRUCTURE
          - UPDATE_ISSUES
      - name: user2
  web-conf-c:
    users:
      - name: user1
        grants:
          - FAKE
          - UPDATE_CASES
  web-conf-d:
    data-formats:
      yabba:
        receipt-number-key: customReceiptNumber
      dabba:
        creation-date-key: "whenever"
      doo:
        creation-date-format: "EEE MMM dd yyyy" # Wed May 7 2031
  oauth-conf-a:
    name-path:
      - yabba
      - dabba
      - doo
    authority-paths:
      - authority: UPDATE_ISSUES
        path: custom, attribute, path
