logging:
  level:
      org.hibernate:
        SQL: DEBUG
        stat: ERROR
      gov.usds.case_issues: DEBUG
      org.springframework.security.access: DEBUG
spring:
  profiles:
    include: autotest-local
  datasource:
    username: case_issue_api
    url: jdbc:postgresql://localhost:${CASEISSUES_TEST_DB_PORT:5400}/case_issues
  jpa:
    properties:
      hibernate:
        default_schema: case_issue_main
        format_sql: true
        generate_statistics: false # way too noisy to be worth it
    hibernate.ddl-auto: none
  liquibase:
    enabled: true
    user: case_issue_migrations
web-customization:
  cors-origins:
    - http://ok-client.net
    - https://ok-client.gov
authorization:
  grants:
    x509:
        - authorities: read-cases, update-cases, manage-application
          match-condition: 'CN=alice, O=No Such Agency, L=Washington, ST=DC, C=US'
          terminal: true
        - authorities: UPDATE_ISSUES
          match-condition:
            - 'CN=bob, O=No Such Agency, L=Washington, ST=DC, C=US'
          terminal: true
# this is probably not needed in the long run, but for now X509MappingConfig is conditional on it being set
server.ssl.client-auth: none
bind-testing:
  web-conf-a:
    cors-origins:
      - http://origin
      - https://other-origin
  web-conf-d:
    data-formats:
      yabba:
        receipt-number-key: customReceiptNumber
      dabba:
        creation-date-key: "whenever"
      doo:
        creation-date-format: "EEE MMM dd yyyy" # Wed May 7 2031
  web-conf-e:
    additional-http-port: 23
  oauth-conf-a:
    name-path:
      - yabba
      - dabba
      - doo
    authority-paths:
      - authority: UPDATE_ISSUES
        path: custom, attribute, path
  auth-conf-a:
    grants.test:
      - name: user1
        authorities:
          - READ_CASES
          - update-cases
          - updateStructure
          - UPDATE_ISSUES
      - name: user2
  auth-conf-b:
    grants.test:
      - name: user1
        authorities:
          - FAKE
          - UPDATE_CASES
  auth-conf-c:
    grants.magical:
      - name: user1
        authorities:
          - UPDATE_CASES
  auth-conf-d:
    grants.x509:
      - name: user1
        match-condition: "a, b, c, d"
        authorities: manage-application
      - name: user2
        match-condition:
          - "q, w, e, rty"
        authorities: read-cases
  auth-conf-e:
    oauth-id-path:
      - yabba
      - dabba
      - doo
    grants.oauth:
      - authorities: UPDATE_ISSUES
        match-condition: custom, attribute, path
