version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build test image
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
      - run:
          name: Run all checks
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from check check
      - run:
          name: Retrieve test results and reports
          command: |
            image_id=$(docker-compose -f docker-compose.yml -f docker-compose.ci.yml ps -q check);
            echo "Found ${image_id}"
            docker cp ${image_id}:/home/gradle/case-issue-api/build/test-results docker-test-results;
            docker cp ${image_id}:/home/gradle/case-issue-api/build/reports docker-reports;
      - store_test_results:
          path: docker-test-results
      - store_artifacts:
          path: docker-reports/jacoco/test/html
          destination: coverage
      - store_artifacts:
          path: docker-reports/checkstyle
          destination: checkstyle
