version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build test image
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.test.yml build
      - run:
          name: Run all checks
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from check check
      - store_test_results:
          path: docker-build/test-results
      - store_artifacts:
          path: docker-build/reports/jacoco/test/html
          destination: coverage
      - store_artifacts:
          path: docker-build/reports/checkstyle
          destination: checkstyle
